### ISSUE TITLE
uxy ls doesn't handle file names with spaces

### ISSUE THREAD

**Issue by Keith-S-Thompson** [sustrik/uxy#4]
If `uxy ls` encounters a file with a space in its name, it ignores the portion of the file name after the space.

I haven't checked other funny characters (for example, it's legal to have a newline in a filename).

On my system, Ubuntu 18.04:

    $ ls -l
    total 28
    -rw-r--r-- 1 kst kst  8585 May 20 11:18 README.md
    -rwxr-xr-x 1 kst kst 13522 May 20 11:18 uxy
    $ uxy ls
    TYPE PERMISSIONS LINKS OWNER      GROUP      SIZE         TIME                                  NAME
    -    rw-r--r--   1     kst        kst        8585         "2019-05-20 11:18:33.459647439 -0700" README.md
    -    rwxr-xr-x   1     kst        kst        13522        "2019-05-20 11:18:33.459647439 -0700" uxy
    $ touch 'foo bar'
    $ uxy ls
    TYPE PERMISSIONS LINKS OWNER      GROUP      SIZE         TIME                                  NAME
    -    rw-r--r--   1     kst        kst        8585         "2019-05-20 11:18:33.459647439 -0700" README.md
    -    rw-r--r--   1     kst        kst        0            "2019-05-20 11:24:36.350283775 -0700" foo
    -    rwxr-xr-x   1     kst        kst        13522        "2019-05-20 11:18:33.459647439 -0700" uxy
    $

**Comment by sustrik** [comment]
Fixed.
